### ISSUE TITLE
Blacken is opening to many processes

### ISSUE THREAD

**Issue by Aaronzinhoo** [proofit404/blacken#48] opened 2022-03-02 10:44 UTC
I am using emacs 28.0.50 on Mac Monterey and am experiencing a "too many files" open error. After looking at the processes list I see that blacken has many open ones. Specifically blacken-error, All I did was automatically start blacken when opening a python file.

```

(use-package blacken
  :diminish ""
  :custom
  (blacken-skip-string-normalization t)
  (blacken-line-length 120))
(use-package python
  :delight " Py"
  :mode ("\\.py" . python-mode)
  :hook ((python-mode . pyvenv-mode)
         (python-mode . blacken-mode)
         (python-mode . (lambda () (aaronzinhoo--python-setup))))
  :preface
  (defun aaronzinhoo--python-buffer-setup ()
    (setq python-indent-offset 4)
    (setq-local highlight-indentation-offset 4))
  (defun aaronzinhoo--activate-python-shell-complettion ()
    "Return non-nil if can trigger native completion."
    (let ((python-shell-completion-native-enable t)
          (python-shell-completion-native-output-timeout
           python-shell-completion-native-try-output-timeout))
      (python-shell-completion-native-get-completions
       (get-buffer-process (current-buffer))
       nil "_")))
  ;;https://lists.gnu.org/archive/html/help-gnu-emacs/2021-09/msg00535.html
  ;; used to help pyright find venv folders
  (defun aaronzinhoo--pyvenv-workon ()
    (when (buffer-file-name)
      (let* ((python-version ".python-version")
             (project-dir (locate-dominating-file (buffer-file-name) python-version)))
        (when project-dir
	      (progn
	        ;; https://github.com/emacs-lsp/lsp-pyright/issues/62#issuecomment-942845406
	        (lsp-workspace-folders-add project-dir)
	        (pyvenv-workon
             (with-temp-buffer
               (insert-file-contents (expand-file-name python-version project-dir))
               (car (split-string (buffer-string))))))))))
  (defun aaronzinhoo--python-setup ()
    (aaronzinhoo--python-buffer-setup)
    (aaronzinhoo--pyvenv-workon))
  :custom
  (python-check-command "flake8")
  :init
  (setenv "WORKON_HOME" "~/.pyenv/versions")
  (add-to-list 'process-coding-system-alist '("python" . (utf-8 . utf-8)))
  (with-eval-after-load 'python (defun temp () (aaronzinhoo--activate-python-shell-complettion))))
```

![image](https://user-images.githubusercontent.com/26849064/156346556-b309d7f4-cc4e-445c-8c73-6e1767c552f9.png)

**Comment by dakra** [comment] 2022-03-02 12:09
Duplicate of https://github.com/pythonic-emacs/blacken/issues/27

PRs for a fix are welcome. (Personally I don't use blacken anymore)

**Closed as completed by dakra** 2022-03-02 12:09 UTC

**Comment by sbroberg** [comment] 2024-04-03 18:35
https://github.com/pythonic-emacs/blacken/pull/59

I've submitted a PR to address this issue.  On my machine, anyway, the leaking resources is due to the make-process command failing when it couldn't find an executable called "black".  I'm not sure how this is to work on windows, as on the machines I use, python modules do not get promoted to standalone commands by the shell.

Changing the blacken executable to a list allows us to override the default name with something like:

```
(custom-set-variables
  '(blacken-executable-list '("python3.exe" "-m" "black"))
)
```
